import { GoogleGenAI } from '@google/genai';
import { SYSTEM_PROMPT } from '../prompt';

export interface ProductData {
  title: string;
  price: number;
  rating: number;
  reviews: number;
  category: string;
  estimated_sales: number;
  cost_price: number;
}

export interface EvaluationResult {
  product_title: string;
  category: string;
  price: number;
  estimated_profit_margin: number;
  demand_score: number;
  competition_score: number;
  risk_level: 'Low' | 'Medium' | 'High';
  fba_friendly: boolean;
  scalability_score: number;
  confidence_score: number;
  final_verdict: 'WINNER' | 'AVOID';
  reason: string;
  improvement_suggestions: string[];
}

export async function evaluateProduct(data: ProductData): Promise<EvaluationResult> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is not set. Please configure it safely via the AI Studio platform.');
  }

  const ai = new GoogleGenAI({ apiKey });

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-pro',
    contents: JSON.stringify(data, null, 2),
    config: {
      systemInstruction: SYSTEM_PROMPT,
      temperature: 0.1, // Ensure strict JSON evaluation and reasoning
    },
  });

  if (!response.text) {
    throw new Error('No evaluation generated by the Intelligence Agent.');
  }

  let rawJson = response.text().trim();
  // Strip markdown formatting if any exists
  if (rawJson.startsWith('```json')) {
    rawJson = rawJson.replace(/^```json/, '').replace(/```$/, '').trim();
  } else if (rawJson.startsWith('```')) {
    rawJson = rawJson.replace(/^```/, '').replace(/```$/, '').trim();
  }

  try {
    const result = JSON.parse(rawJson) as EvaluationResult;
    return result;
  } catch (err) {
    console.error('JSON Parsing Error:', rawJson);
    throw new Error('Intelligence Agent returned corrupted JSON.');
  }
}
